version: 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:current

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      
      - run:
          name: Get Docker version
          command: echo "export APP_VERSION=$(cat version.txt)" >> $BASH_ENV

      - run:
          name: Output Docker version
          command: echo $APP_VERSION

      - run:
          name: Install Docker Buildx
          command: |
            sudo apt update
            sudo apt install -y docker.io
            docker buildx create --use --name mybuilder --driver docker-container

      - run:
          name: Login to Docker Registry
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login registry.alexbissessur.dev -u "$DOCKERHUB_USERNAME" --password-stdin
          environment:
            DOCKERHUB_USERNAME: << pipeline.parameters.dockerhub_username >>
            DOCKERHUB_TOKEN: << pipeline.parameters.dockerhub_token >>

      - run:
          name: Build and Push Docker Image
          command: |
            docker buildx build --platform linux/amd64,linux/arm64 . \
              -t registry.alexbissessur.dev/meetups:$APP_VERSION --push

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: main

parameters:
  dockerhub_username:
    type: string
  dockerhub_token:
    type: string