apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meetups
  name: meetups
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meetups
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meetups
    spec:
      initContainers:
        - name: migrate
          image: registry.alexbissessur.dev/meetups:4.25
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: env-cfm
            - secretRef:
                name: app-key
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_DATABASE
      containers:
        - image: registry.alexbissessur.dev/meetups:4.25
          name: meetups
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-cfm
            - secretRef:
                name: mail-secret
            - secretRef:
                name: app-key

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_PASSWORD

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_DATABASE
          imagePullPolicy: Always

      imagePullSecrets:
        - name: regcred
