apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meetups
  name: meetups
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meetups
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meetups
    spec:
      containers:
        - image: registry.alexbissessur.dev/meetups:2.7
          name: meetups
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-cfm
          imagePullPolicy: Always

      imagePullSecrets:
        - name: regcred
