# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-24.04-arm

#     steps:
#         - name: Login to Docker Hub
#           uses: docker/login-action@v3
#           with:
#             registry: registry.alexbissessur.dev
#             username: ${{ vars.DOCKERHUB_USERNAME }}
#             password: ${{ secrets.DOCKERHUB_TOKEN }}

#         - uses: actions/checkout@v4

#         - name: Get Docker version
#           run: echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV

#         - name: Output Docker ver
#           run: echo $APP_VERSION

#         - name: Get valid builder
#           run: docker buildx create --use --name mybuilder --driver docker-container

#         - name: Build and push Docker image
#           run: docker buildx build --platform linux/arm64 . -t registry.alexbissessur.dev/meetups:$APP_VERSION --push
