name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}

    steps:
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.alexbissessur.dev
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Get Docker version
        run: echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Output Docker ver
        run: echo $APP_VERSION

      # - name: Build and Push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     platforms: linux/${{ matrix.arch }}
      #     tags: registry.alexbissessur.dev/meetups:${{ env.APP_VERSION }}-${{ matrix.arch }}
      - name: Build
        run: docker build -t registry.alexbissessur.dev/meetups:${{ env.APP_VERSION }}-${{ matrix.arch }} .

      - name: Push
        run: docker push registry.alexbissessur.dev/meetups:${{ env.APP_VERSION }}-${{ matrix.arch }}

  merge-manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.alexbissessur.dev
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Get Docker version
        run: echo "APP_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Output Docker ver
        run: echo $APP_VERSION

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create registry.alexbissessur.dev/meetups:${{env.APP_VERSION}} \
            registry.alexbissessur.dev/meetups:${{env.APP_VERSION}}-amd64 \
            registry.alexbissessur.dev/meetups:${{env.APP_VERSION}}-arm64
          docker manifest push registry.alexbissessur.dev/meetups:${{env.APP_VERSION}}
